const Constants = {
  LOGIN_ACTION: 'LOGIN_ACTION',
  LOGIN_SUCCES: 'LOGIN_SUCCES',
  CREATE_NOTE: 'CREATE_NOTE',
  GET_NOTES: 'GET_NOTES',
  PUT_NOTES_TO_STATE: 'PUT_NOTES_TO_STATE'
}
export default Constants
